#name: Waka Readme
#
#on:
#  schedule:
#    # Runs at 12am IST
#    - cron: '30 18 * * *'
#  workflow_dispatch:
#jobs:
#  update-readme:
#    name: Update Readme with Metrics
#    runs-on: ubuntu-latest
#    steps:
#      - uses: anmol098/waka-readme-stats@master
#        with:
#          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#          SHOW_OS: "False"
#          SHOW_PROJECTS: "False"

name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'  # Runs at 12am IST
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_PROJECTS: "True"  # ✅ Show projects
          SHOW_OS: "False"
          SHOW_EDITORS: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_UPDATED_DATE: "True"  # ✅ Show last updated date
          SHOW_LOC_CHART: "False"  # ❌ Hide LOC chart
          SECTION_NAME: "waka"
          COMMIT_BY_ME: "True"  # ✅ Commit using your GitHub name/email
